name: Build for macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller main.py --onefile --name=Neg2Posi

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: Neg2Posi-macOS
        path: dist/Neg2Posi